# Generated by Django 5.2.16 on 2026-08-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="primary_need_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "LEARN_ORGANISE",
                        "Learn new concepts and organise learning materials",
                    ),
                    (
                        "PRACTISE_RETAIN",
                        "Practise and retain knowledge with cards and reviews",
                    ),
                    (
                        "INTERVIEW_SKILLS",
                        "Build interview skills with stories, evidence and mocks",
                    ),
                ],
                default="",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="secondary_need_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "LEARN_ORGANISE",
                        "Learn new concepts and organise learning materials",
                    ),
                    (
                        "PRACTISE_RETAIN",
                        "Practise and retain knowledge with cards and reviews",
                    ),
                    (
                        "INTERVIEW_SKILLS",
                        "Build interview skills with stories, evidence and mocks",
                    ),
                ],
                default="",
                max_length=24,
            ),
        ),
    ]
