# Generated by Django 5.2.16 on 2026-07-21 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('prompt', models.TextField()),
                ('question_type', models.CharField(choices=[('TECHNICAL', 'Technical'), ('BEHAVIOURAL', 'Behavioural'), ('DEBUG', 'Repository debugging')], editable=False, max_length=20)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('difficulty', models.CharField(blank=True, choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BehaviouralQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.question')),
                ('star_answer', models.TextField(blank=True)),
                ('leadership_principles', models.TextField(blank=True, help_text='Competencies, values or leadership principles this answer demonstrates.')),
                ('stories', models.TextField(blank=True)),
                ('follow_ups', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'behavioural question',
                'verbose_name_plural': 'behavioural questions',
            },
            bases=('questions.question',),
        ),
        migrations.CreateModel(
            name='DebugQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.question')),
                ('repository', models.CharField(blank=True, max_length=160)),
                ('bug_type', models.CharField(blank=True, choices=[('SORTING', 'Broken sorting'), ('MISSING_FIELD', 'Missing field'), ('WRONG_COMPARISON', 'Wrong comparison'), ('INCORRECT_DEFAULT', 'Incorrect default'), ('NULL_HANDLING', 'Null handling'), ('KEY_TYPO', 'Dictionary key typo'), ('OFF_BY_ONE', 'Off-by-one'), ('API_RESPONSE', 'Wrong API response'), ('OTHER', 'Other')], max_length=30)),
                ('broken_code', models.TextField(blank=True)),
                ('fix', models.TextField(blank=True)),
                ('tests', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'debugging question',
                'verbose_name_plural': 'debugging questions',
            },
            bases=('questions.question',),
        ),
        migrations.CreateModel(
            name='TechnicalQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.question')),
                ('topic', models.CharField(blank=True, max_length=120)),
                ('first_hint', models.TextField(blank=True)),
                ('pattern', models.CharField(blank=True, max_length=120)),
                ('data_structure', models.CharField(blank=True, max_length=120)),
                ('intuition', models.TextField(blank=True)),
                ('brute_force', models.TextField(blank=True)),
                ('optimal_approach', models.TextField(blank=True)),
                ('complexity', models.CharField(blank=True, max_length=255)),
                ('mistakes', models.TextField(blank=True)),
                ('code', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'technical question',
                'verbose_name_plural': 'technical questions',
            },
            bases=('questions.question',),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['owner', 'status', '-updated_at'], name='question_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['owner', 'question_type'], name='question_owner_type_idx'),
        ),
    ]
