# Generated by Django 5.2.16 on 2026-07-21 23:36

import apps.questions.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def migrate_question_statuses(apps, schema_editor):
    Question = apps.get_model("questions", "Question")
    Question.objects.filter(status="DRAFT").update(status="NEEDS_NOTES")
    Question.objects.filter(status="ACTIVE").update(status="READY_FOR_REVIEW")


def reverse_question_statuses(apps, schema_editor):
    Question = apps.get_model("questions", "Question")
    Question.objects.filter(status="NEEDS_NOTES").update(status="DRAFT")
    Question.objects.filter(status="READY_FOR_REVIEW").update(status="ACTIVE")


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_creation_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('NEEDS_NOTES', 'Needs notes'), ('READY_FOR_REVIEW', 'Ready for review'), ('ARCHIVED', 'Archived')], default='NEEDS_NOTES', max_length=20),
        ),
        migrations.RunPython(migrate_question_statuses, reverse_question_statuses),
        migrations.CreateModel(
            name='QuestionImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('PASTE', 'Pasted text'), ('TXT', 'Text file'), ('MARKDOWN', 'Markdown file'), ('CSV', 'CSV file'), ('DOCX', 'Word document'), ('PDF', 'PDF document')], max_length=20)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('default_question_type', models.CharField(choices=[('TECHNICAL', 'Technical'), ('BEHAVIOURAL', 'Behavioural'), ('DEBUG', 'Repository debugging')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY_FOR_REVIEW', 'Ready for review'), ('IMPORTING', 'Importing'), ('IMPORTED', 'Imported'), ('FAILED', 'Failed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_question_count', models.PositiveIntegerField(default=0)),
                ('temporary_file', models.FileField(blank=True, upload_to=apps.questions.models.question_import_upload_to)),
                ('source_text', models.TextField(blank=True)),
                ('failure_message', models.TextField(blank=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to='questions.questionimportbatch'),
        ),
        migrations.CreateModel(
            name='QuestionImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('generated_title', models.CharField(max_length=180)),
                ('question_text', models.TextField()),
                ('normalized_text', models.TextField(blank=True)),
                ('question_type', models.CharField(choices=[('TECHNICAL', 'Technical'), ('BEHAVIOURAL', 'Behavioural'), ('DEBUG', 'Repository debugging')], max_length=20)),
                ('is_included', models.BooleanField(default=True)),
                ('duplicate_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='questions.questionimportbatch')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='questionimportbatch',
            index=models.Index(fields=['owner', 'status', '-created_at'], name='qimport_owner_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionimportitem',
            constraint=models.UniqueConstraint(fields=('batch', 'position'), name='unique_question_import_position'),
        ),
    ]
