# Generated by Django 5.2.16 on 2026-08-01 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0006_question_source_system_question"),
        ("roadmaps", "0004_roadmap_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionGenerationBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes_snapshot", models.TextField()),
                ("requested_count", models.PositiveSmallIntegerField(default=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GENERATING", "Generating"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                        ],
                        default="GENERATING",
                        max_length=16,
                    ),
                ),
                ("generation_model", models.CharField(blank=True, max_length=120)),
                ("created_question_count", models.PositiveSmallIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="question",
            name="question_system_owner_consistency",
        ),
        migrations.AddField(
            model_name="question",
            name="source_topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_questions",
                to="roadmaps.roadmaptopic",
            ),
        ),
        migrations.AddField(
            model_name="questiongenerationbatch",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_generation_batches",
                to="roadmaps.roadmaptopic",
            ),
        ),
        migrations.AddField(
            model_name="questiongenerationbatch",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_generation_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="generation_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_questions",
                to="questions.questiongenerationbatch",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("generation_batch__isnull", True),
                        ("import_batch__isnull", True),
                        ("is_system", True),
                        ("owner__isnull", True),
                        ("source_system_question__isnull", True),
                        ("source_topic__isnull", True),
                        ("system_key__isnull", False),
                    ),
                    models.Q(
                        ("is_system", False),
                        ("owner__isnull", False),
                        ("system_key__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="question_system_owner_consistency",
            ),
        ),
        migrations.AddIndex(
            model_name="questiongenerationbatch",
            index=models.Index(
                fields=["user", "topic", "-created_at"],
                name="qgen_user_topic_created_idx",
            ),
        ),
    ]
