from django.urls import path

from . import course_views, custom_views, views, youtube_views

app_name = "roadmaps"

urlpatterns = [
    path("", views.roadmap_list, name="list"),
    path(
        "custom/",
        custom_views.custom_roadmap_list,
        name="custom_list",
    ),
    path(
        "custom/create/",
        custom_views.create_custom_roadmap_view,
        name="custom_create",
    ),
    path(
        "custom/<slug:slug>/manage/",
        custom_views.manage_custom_roadmap,
        name="custom_manage",
    ),
    path(
        "custom/<slug:slug>/edit/",
        custom_views.edit_custom_roadmap,
        name="custom_edit",
    ),
    path(
        "custom/<slug:slug>/focus/",
        custom_views.toggle_custom_roadmap_focus,
        name="custom_focus",
    ),
    path(
        "custom/<slug:slug>/delete/",
        custom_views.delete_custom_roadmap_view,
        name="custom_delete",
    ),
    path(
        "custom/<slug:slug>/modules/create/",
        custom_views.create_custom_section_view,
        name="custom_section_create",
    ),
    path(
        "custom/<slug:slug>/modules/<int:section_id>/edit/",
        custom_views.edit_custom_section,
        name="custom_section_edit",
    ),
    path(
        "custom/<slug:slug>/modules/<int:section_id>/move/",
        custom_views.move_custom_section_view,
        name="custom_section_move",
    ),
    path(
        "custom/<slug:slug>/modules/<int:section_id>/delete/",
        custom_views.delete_custom_section_view,
        name="custom_section_delete",
    ),
    path(
        "custom/<slug:slug>/modules/<int:section_id>/topics/create/",
        custom_views.create_custom_topic_view,
        name="custom_topic_create",
    ),
    path(
        "custom/<slug:slug>/topics/<int:topic_id>/edit/",
        custom_views.edit_custom_topic,
        name="custom_topic_edit",
    ),
    path(
        "custom/<slug:slug>/topics/<int:topic_id>/move/",
        custom_views.move_custom_topic_view,
        name="custom_topic_move",
    ),
    path(
        "custom/<slug:slug>/topics/<int:topic_id>/delete/",
        custom_views.delete_custom_topic_view,
        name="custom_topic_delete",
    ),
    path(
        "courses/import/ibm/confirm/",
        course_views.ibm_course_confirm,
        name="ibm_course_confirm",
    ),
    path(
        "courses/import/ibm/",
        course_views.ibm_course_import,
        name="ibm_course_import",
    ),
    path(
        "courses/",
        course_views.course_roadmap_list,
        name="course_list",
    ),
    path(
        "courses/<slug:slug>/focus/",
        course_views.toggle_course_focus,
        name="course_focus",
    ),
    path(
        "courses/<slug:slug>/delete/",
        course_views.delete_course_roadmap,
        name="course_delete",
    ),
    path(
        "youtube/groups/create/",
        youtube_views.create_youtube_group,
        name="youtube_group_create",
    ),
    path(
        "youtube/groups/<int:group_id>/rename/",
        youtube_views.rename_youtube_group,
        name="youtube_group_rename",
    ),
    path(
        "youtube/groups/<int:group_id>/delete/",
        youtube_views.delete_youtube_group,
        name="youtube_group_delete",
    ),
    path(
        "youtube/import/confirm/",
        youtube_views.youtube_playlist_confirm,
        name="youtube_import_confirm",
    ),
    path(
        "youtube/import/",
        youtube_views.youtube_playlist_import,
        name="youtube_import",
    ),
    path(
        "youtube/",
        youtube_views.youtube_roadmap_list,
        name="youtube_list",
    ),
    path(
        "youtube/<slug:slug>/favourite/",
        youtube_views.toggle_youtube_favourite,
        name="youtube_favourite",
    ),
    path(
        "youtube/<slug:slug>/move/",
        youtube_views.move_youtube_roadmap,
        name="youtube_move",
    ),
    path(
        "youtube/<slug:slug>/videos/<int:topic_id>/complete/",
        youtube_views.complete_youtube_video,
        name="youtube_video_complete",
    ),
    path(
        "youtube/<slug:slug>/videos/<int:topic_id>/",
        youtube_views.youtube_video_detail,
        name="youtube_video_detail",
    ),
    path(
        "youtube/<slug:slug>/delete/",
        youtube_views.delete_youtube_roadmap,
        name="youtube_delete",
    ),
    path(
        "youtube/<slug:slug>/",
        youtube_views.youtube_roadmap_detail,
        name="youtube_detail",
    ),
    # Compatibility aliases for existing bookmarks and forms.
    path(
        "<slug:slug>/youtube/delete/",
        youtube_views.delete_youtube_roadmap,
        name="delete_youtube_roadmap",
    ),
    path(
        "<slug:slug>/focus/",
        views.toggle_roadmap_focus,
        name="focus",
    ),
    path("<slug:slug>/", views.roadmap_detail, name="detail"),
    path("<slug:slug>/start/", views.start_roadmap, name="start"),
    path(
        "<slug:slug>/topics/<int:topic_id>/",
        views.topic_detail,
        name="topic_detail",
    ),
    path(
        "<slug:slug>/topics/<int:topic_id>/status/",
        views.update_topic_status,
        name="update_topic_status",
    ),
    path(
        "<slug:slug>/topics/<int:topic_id>/notes/",
        views.save_topic_notes,
        name="save_topic_notes",
    ),
    path(
        "<slug:slug>/topics/<int:topic_id>/questions/generate/",
        views.generate_topic_questions,
        name="generate_topic_questions",
    ),
    path(
        "<slug:slug>/topics/<int:topic_id>/questions/<int:batch_id>/",
        views.topic_question_drafts,
        name="topic_question_drafts",
    ),
    path(
        "<slug:slug>/topics/<int:topic_id>/resources/",
        views.add_topic_resource,
        name="add_topic_resource",
    ),
    path(
        ("<slug:slug>/topics/<int:topic_id>/resources/<int:resource_id>/delete/"),
        views.delete_topic_resource,
        name="delete_topic_resource",
    ),
    path(
        "<slug:slug>/topics/<int:topic_id>/youtube/complete/",
        youtube_views.complete_youtube_video,
        name="complete_youtube_video",
    ),
]
