# Generated by Django 5.2 on 2026-07-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Roadmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ROLE", "Career roadmap"),
                            ("SKILL", "Skill roadmap"),
                            ("PRACTICE", "Practice roadmap"),
                        ],
                        max_length=12,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_system", models.BooleanField(default=True)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_roadmaps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["position", "title"],
                "indexes": [
                    models.Index(
                        fields=["kind", "is_published", "position"],
                        name="roadmap_kind_pub_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RoadmapSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("slug", models.SlugField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "roadmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="roadmaps.roadmap",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "title"],
                "indexes": [
                    models.Index(
                        fields=["roadmap", "position"],
                        name="section_roadmap_pos_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("roadmap", "slug"),
                        name="unique_section_slug",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RoadmapTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="roadmaps.roadmapsection",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "title"],
                "indexes": [
                    models.Index(
                        fields=["section", "position"],
                        name="topic_section_pos_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("section", "slug"),
                        name="unique_topic_slug",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserRoadmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not started"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="NOT_STARTED",
                        max_length=16,
                    ),
                ),
                ("target_date", models.DateField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "roadmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_enrolments",
                        to="roadmaps.roadmap",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmap_enrolments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "status"],
                        name="user_roadmap_status_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "roadmap"),
                        name="unique_user_roadmap",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserTopicProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not started"),
                            ("IN_PROGRESS", "Learning"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="NOT_STARTED",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="roadmaps.roadmaptopic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "status"],
                        name="user_topic_status_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "topic"),
                        name="unique_user_topic_progress",
                    )
                ],
            },
        ),
    ]
